### ISSUE TITLE
Queue stuck on same item after each get()

### ISSUE THREAD

**Issue by sionking** [peter-wangxu/persist-queue#86]
I am having this queue running for over 200 instances of my application.
I checked the logs of one instance and I saw itemX was inserted once.

Latter I get the item:
`Globals.validated_profiles_queue.get(block=False)`
this will return me "shahar.ha" which is **itemX**.
Then each time I do "get" I will find "shahar.ha" as the item~~!!!~~

The data files:
* IN COMMENT

Please assist.

OS: Windows 7
NOT multithreded
Simple put and get.

**Comment by sionking** [comment]
[valid_users_q.zip](https://github.com/peter-wangxu/persist-queue/files/2669791/valid_users_q.zip)

**Comment by peter-wangxu** [comment]
is there any sample/pseudo code?

**Comment by sionking** [comment]
Set:
```
# store the results in queue until it reach self.max_q
Globals.validated_profiles_queue.put((self.currentUsernameSource, username, details, return_values_dist))
# parse the queue item
username = queue_item[1]
details = queue_item[2]
return_values_dist = queue_item[3]
```
Get:
`Globals.validated_profiles_queue.get(block=False)`

Nothing else.
I do use dropbox to sync files, maybe it corrupted the file ?

**Comment by peter-wangxu** [comment]
@sionking 
I successfully reproduced the issue with the data you provided, I also tried with sqlite3 tool, the wired thing is that, i cannot event delete a row by _id(which is the primary key of table), so that's why the queue kept poping the same value as the previous item cannot be deleted from table. I wonder if the dropbox corrupted the sqlite3 data file some way:)

I suggest putting/getting data without the interference of dropbox and try again.

Thanks
Peter

**Comment by peter-wangxu** [comment]
Closing it, Please reopen it if still exists
